image:
  file: .gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-preview
    visibility: private
  - port: 5900
    onOpen: ignore
    visibility: private

tasks:
  - init: export PATH=/workspace/application-testing-helper:$PATH
  - init: pip install --upgrade pip
  - init: pip install -r ./requirements.txt
