image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./gitpod_setup.sh

ports:
  - port: 6080
    onOpen: open-preview
    visibility: private
  - port: 5900
    onOpen: ignore
    visibility: private
