version:                    1
logging_level:              &logging_level  INFO # default INFO, DEBUG to analyze issues
disable_existing_loggers:   False

formatters:
  standard:
    format:                 '{asctime} [{levelname:^8}]: {message}'
    style:                  '{'
#    datefmt:                '%Y-%m-%d-%H:%M:%S'
  debug:
    format:                 '{asctime} [{levelname:^8}] {name}.{funcName}(): {message}'
    style:                  '{'

handlers:
  console:
    class:                  logging.StreamHandler
    level:                  *logging_level
    formatter:              standard
    stream:                 ext://sys.stdout
  standard_log:
    class:                  logging.handlers.RotatingFileHandler
    level:                  *logging_level
    formatter:              standard
    filename:               ./logs/uat.log
    maxBytes:               10485760 # 10 MB
    backupCount:            10
  debug_log:
    class:                  logging.handlers.RotatingFileHandler
    level:                  DEBUG
    formatter:              debug
    filename:               ./logs/uat_debug.log
    maxBytes:               10485760 # 10 MB
    backupCount:            10

root:
  level:                    NOTSET
  handlers:                 [console,standard_log,debug_log]
